// Mock data for Management page
import type { Employee, Club, Section, Tariff, Group, Schedule } from './types';

export const mockClubs: Club[] = [
  { id: 1, name: 'Фитнес клуб "Сила"', status: 'active' },
  { id: 2, name: 'Спортзал "Энергия"', status: 'active' },
  { id: 3, name: 'Клуб "Олимп"', status: 'frozen' },
];

export const mockEmployees: Employee[] = [
  {
    id: 1,
    first_name: 'Алексей',
    last_name: 'Петров',
    phone: '+7 777 111 22 33',
    telegram_username: 'alex_petrov',
    role: 'owner',
    status: 'active',
    club_ids: [1, 2],
    created_at: '2024-01-15T10:00:00Z',
  },
  {
    id: 2,
    first_name: 'Мария',
    last_name: 'Иванова',
    phone: '+7 777 222 33 44',
    telegram_username: 'maria_iv',
    role: 'admin',
    status: 'active',
    club_ids: [1],
    created_at: '2024-02-20T10:00:00Z',
  },
  {
    id: 3,
    first_name: 'Дмитрий',
    last_name: 'Сидоров',
    phone: '+7 777 333 44 55',
    telegram_username: 'dmitry_sid',
    role: 'trainer',
    status: 'active',
    club_ids: [1, 2],
    created_at: '2024-03-10T10:00:00Z',
  },
  {
    id: 4,
    first_name: 'Елена',
    last_name: 'Козлова',
    phone: '+7 777 444 55 66',
    telegram_username: 'elena_k',
    role: 'trainer',
    status: 'active',
    club_ids: [1],
    created_at: '2024-04-05T10:00:00Z',
  },
  {
    id: 5,
    first_name: 'Сергей',
    last_name: 'Новиков',
    phone: '+7 777 555 66 77',
    telegram_username: 'sergey_n',
    role: 'trainer',
    status: 'pending',
    club_ids: [2],
    created_at: '2024-10-01T10:00:00Z',
  },
  {
    id: 6,
    first_name: 'Анна',
    last_name: 'Белова',
    phone: '+7 777 666 77 88',
    telegram_username: 'anna_b',
    role: 'admin',
    status: 'deactivated',
    club_ids: [1],
    created_at: '2024-05-15T10:00:00Z',
  },
];

const mockSchedules: Schedule[] = [
  {
    id: 1,
    group_id: 1,
    type: 'recurring',
    start_date: '2024-10-01',
    start_time: '09:00',
    duration: 60,
    days_of_week: ['mon', 'wed', 'fri'],
    end_date: '2024-12-31',
  },
  {
    id: 2,
    group_id: 2,
    type: 'recurring',
    start_date: '2024-10-01',
    start_time: '18:00',
    duration: 90,
    days_of_week: ['tue', 'thu'],
    end_date: '2024-12-31',
  },
  {
    id: 3,
    group_id: 3,
    type: 'recurring',
    start_date: '2024-10-01',
    start_time: '10:00',
    duration: 60,
    days_of_week: ['mon', 'wed', 'fri', 'sat'],
    end_date: '2024-12-31',
  },
];

const mockGroups: Group[] = [
  // Йога groups (section 1)
  {
    id: 1,
    section_id: 1,
    name: 'Начинающие',
    level: 'beginner',
    capacity: 15,
    schedules: mockSchedules.filter(s => s.group_id === 1),
  },
  {
    id: 2,
    section_id: 1,
    name: 'Продвинутые',
    level: 'advanced',
    capacity: 10,
    schedules: mockSchedules.filter(s => s.group_id === 2),
  },
  // Пилатес groups (section 2)
  {
    id: 3,
    section_id: 2,
    name: 'Утренняя группа',
    level: 'all',
    capacity: 20,
    schedules: mockSchedules.filter(s => s.group_id === 3),
  },
  {
    id: 4,
    section_id: 2,
    name: 'Вечерняя группа',
    level: 'all',
    capacity: 15,
    schedules: [],
  },
  // Кроссфит groups (section 3)
  {
    id: 5,
    section_id: 3,
    name: 'WOD Утро',
    level: 'intermediate',
    capacity: 12,
    schedules: [],
  },
  {
    id: 6,
    section_id: 3,
    name: 'WOD Вечер',
    level: 'advanced',
    capacity: 10,
    schedules: [],
  },
  // Бокс groups (section 4)
  {
    id: 7,
    section_id: 4,
    name: 'Новички',
    level: 'beginner',
    capacity: 15,
    schedules: [],
  },
  {
    id: 8,
    section_id: 4,
    name: 'Спарринг',
    level: 'advanced',
    capacity: 8,
    schedules: [],
  },
];

export const mockSections: Section[] = [
  {
    id: 1,
    name: 'Йога',
    club_id: 1,
    club_name: 'Фитнес клуб "Сила"',
    trainer_ids: [3, 4],
    trainers: [
      { id: 3, name: 'Дмитрий Сидоров' },
      { id: 4, name: 'Елена Козлова' },
    ],
    groups: mockGroups.filter(g => g.section_id === 1),
    created_at: '2024-01-20T10:00:00Z',
  },
  {
    id: 2,
    name: 'Пилатес',
    club_id: 1,
    club_name: 'Фитнес клуб "Сила"',
    trainer_ids: [4],
    trainers: [{ id: 4, name: 'Елена Козлова' }],
    groups: mockGroups.filter(g => g.section_id === 2),
    created_at: '2024-02-15T10:00:00Z',
  },
  {
    id: 3,
    name: 'Кроссфит',
    club_id: 1,
    club_name: 'Фитнес клуб "Сила"',
    trainer_ids: [3],
    trainers: [{ id: 3, name: 'Дмитрий Сидоров' }],
    groups: [],
    created_at: '2024-03-01T10:00:00Z',
  },
  {
    id: 4,
    name: 'Бокс',
    club_id: 2,
    club_name: 'Спортзал "Энергия"',
    trainer_ids: [3, 5],
    trainers: [
      { id: 3, name: 'Дмитрий Сидоров' },
      { id: 5, name: 'Сергей Новиков' },
    ],
    groups: [],
    created_at: '2024-04-10T10:00:00Z',
  },
];

export const mockTariffs: Tariff[] = [
  {
    id: 1,
    name: 'Йога Начинающие - месяц',
    type: 'single_group',
    payment_type: 'monthly',
    price: 25000,
    club_ids: [],
    section_ids: [],
    group_ids: [1],
    active: true,
    created_at: '2024-01-25T10:00:00Z',
  },
  {
    id: 2,
    name: 'Вся Йога - полгода',
    type: 'full_section',
    payment_type: 'semi_annual',
    price: 120000,
    club_ids: [],
    section_ids: [1],
    group_ids: [],
    active: true,
    created_at: '2024-01-25T10:00:00Z',
  },
  {
    id: 3,
    name: 'Полный доступ - Клуб Сила',
    type: 'full_club',
    payment_type: 'annual',
    price: 200000,
    club_ids: [1],
    section_ids: [],
    group_ids: [],
    active: true,
    created_at: '2024-02-01T10:00:00Z',
  },
  {
    id: 4,
    name: '8 занятий Кроссфит',
    type: 'full_section',
    payment_type: 'session_pack',
    price: 28000,
    club_ids: [],
    section_ids: [3],
    group_ids: [],
    sessions_count: 8,
    validity_days: 45,
    active: true,
    created_at: '2024-03-15T10:00:00Z',
  },
  {
    id: 5,
    name: 'Бокс + Кроссфит - месяц',
    type: 'multiple_groups',
    payment_type: 'monthly',
    price: 45000,
    club_ids: [],
    section_ids: [],
    group_ids: [5, 6, 7, 8],
    active: true,
    created_at: '2024-04-20T10:00:00Z',
  },
];

export const levelOptions = [
  { value: 'beginner', label: 'Начинающий' },
  { value: 'intermediate', label: 'Средний' },
  { value: 'advanced', label: 'Продвинутый' },
  { value: 'all', label: 'Все уровни' },
];

export const weekDays = [
  { value: 'mon', label: 'Пн' },
  { value: 'tue', label: 'Вт' },
  { value: 'wed', label: 'Ср' },
  { value: 'thu', label: 'Чт' },
  { value: 'fri', label: 'Пт' },
  { value: 'sat', label: 'Сб' },
  { value: 'sun', label: 'Вс' },
];
